volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:latest
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  migrator:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./calculator/internal/storage/migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "postgres://postgres:password@db:5432/postgres?sslmode=disable", "up" ]

  orchestrator:
    depends_on:
      migrator:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ./docker/orchestrator/Dockerfile
    environment:
      ORCHESTRATOR_HOST: 0.0.0.0
      ORCHESTRATOR_HTTP_PORT: 8080
      ORCHESTRATOR_GRPC_PORT: 8081
      TIME_ADDITION_MS: 100
      TIME_SUBTRACTION_MS: 100
      TIME_MULTIPLICATIONS_MS: 100
      TIME_DIVISIONS_MS: 100
      TASK_MAX_PROCESS_TIME_IN_MS: 30000
      DATABASE_URL: "postgres://postgres:password@db:5432/postgres?sslmode=disable"

  agent:
    depends_on:
      - orchestrator
    build:
      context: .
      dockerfile: ./docker/agent/Dockerfile
    environment:
      ORCHESTRATOR_HOST: orchestrator
      ORCHESTRATOR_HTTP_PORT: 8080
      ORCHESTRATOR_GRPC_PORT: 8081
      AGENT_COMPUTING_POWER: 4

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    volumes:
      - static:/static

  nginx:
    depends_on:
      - orchestrator
    build: ./docker/nginx
    ports:
      - "8081:80"
    volumes:
      - static:/static