services:
  orchestrator:
    container_name: orchestrator
    build:
      context: .
      dockerfile: ./docker/orchestrator/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ORCHESTRATOR_HOST: 0.0.0.0
      ORCHESTRATOR_PORT: 8080
      TIME_ADDITION_MS: 100
      TIME_SUBTRACTION_MS: 100
      TIME_MULTIPLICATIONS_MS: 100
      TIME_DIVISIONS_MS: 100
      TASK_MAX_PROCESS_TIME_IN_MS: 30000

  agent:
    container_name: agent
    build:
      context: .
      dockerfile: ./docker/agent/Dockerfile
    environment:
      ORCHESTRATOR_HOST: orchestrator
      ORCHESTRATOR_PORT: 8080
      COMPUTING_POWER: 4

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
      args:
        BACKEND_SERVER_HOST: 127.0.0.1
        BACKEND_SERVER_PORT: 8080
    ports:
      - "8081:80"
